[context.production.environment]
	HUGO_VERSION = "0.56.0"

[context.branch-deploy.environment]
	HUGO_VERSION = "0.56.0"

[context.deploy-preview.environment]
	HUGO_VERSION = "0.56.0"

[[redirects]]
	from = "https://6-course-sjmd.netlify.com/*"
	to = "https://6.course.sjmd.space/:splat"
	status = 301
	force = true #COMMENT: ensure that we always redirect
